CREATE TABLE t0(c0 name);
CREATE TABLE t1(c0 int4range);
CREATE TABLE t2(LIKE t0);
CREATE TABLE t3(LIKE t0);
CREATE TABLE t4(LIKE t3);
INSERT INTO t1 VALUES('[9,17)');
INSERT INTO t4 VALUES('㘚I8T');
INSERT INTO t1 VALUES('[0,0)');
VACUUM;
INSERT INTO t0 VALUES(('' || 0) COLLATE "C.utf8"), (CAST('' AS VARCHAR)), ('');
CREATE OR REPLACE RECURSIVE VIEW v0(c0)
    AS(SELECT ALL 0.85077786 FROM ONLY t2 t4);
INSERT INTO t3 VALUES(''), (0);
INSERT INTO t2 VALUES(0);
SELECT ALL t2.c0, t0.c0 FROM ONLY t1,
    ONLY t0 LEFT OUTER JOIN ONLY t2 ON(lower(t2.c0)) BETWEEN SYMMETRIC(t2.c0)
        AND(t0.c0 COLLATE "C") CROSS JOIN ONLY v0 LEFT OUTER
    JOIN(SELECT ALL '' FROM t3,
         ONLY t2 WHERE(t3.c0) LIKE(t2.c0)
             AND((FALSE)NOT IN(TRUE, TRUE, TRUE) OR(t3.c0) BETWEEN(t3.c0)
                     AND(t2.c0)) LIMIT 2) AS sub0
    ON(CAST(0 ::INT AS VARCHAR) SIMILAR TO t2.c0) RIGHT OUTER
    JOIN(SELECT ALL 0, t2.c0 FROM ONLY t2, ONLY t4 t1) AS sub1
    ON(CAST(masklen('226.28.137.147') AS VARCHAR)) NOT IN(t0.c0);
