CREATE TABLE a(b int4range, f boolean);
CREATE TABLE c(LIKE a);
CREATE TABLE d(LIKE c);
CREATE TABLE e(LIKE d);
CREATE STATISTICS ON f, b FROM e;
INSERT INTO e VALUES('[4,7)');
ANALYZE;
SELECT MIN(0.7687387293646912) FROM e WHERE(f) ISNULL;
